name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # - name: configure
    #   run: ./configure

    # - name: make all
    #   run: make all

    - name: Create and Zip addon
      run: make addon

    # - name: Run check
    #   run: make check

    # - name: Run distcheck
    #   run: make distcheck
