name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create and Zip addon
      run: make addon

    - name: Upload Zip file
      # if: steps.image-path.outputs.EE_image_pathfilename != ''
      uses: actions/upload-artifact@v4
      with:
        name: "service.eddictwareelec.settings.zip"
        path: "build/service.eddictwareelec.settings-0.0.0.zip"
