name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Calculate SHA256 of commit
      run: |
        PKG_SHA256=$(curl -L "https://github.com/${{ github.repository }}/archive/${{ github.sha }}.tar.gz" | sha256sum)
        echo "PKG_VERSION: ${{ github.sha }}" | tee -a $GITHUB_STEP_SUMMARY
        echo "PKG_SHA256: $PKG_SHA256" | tee -a $GITHUB_STEP_SUMMARY

    - uses: actions/checkout@v7

    - name: Create and Zip addon
      run: make addon

    - name: Upload Zip file
      # if: steps.image-path.outputs.EE_image_pathfilename != ''
      uses: actions/upload-artifact@v7
      with:
        name: "service.eddictwareelec.settings"
        path: "build/service.eddictwareelec.settings-0.0.0.zip"
